services:

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_secret
    ports:
      - "5432:5432"
    networks:
      - neobank-network
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  user-postgres:
    image: postgres:16
    container_name: user-postgres
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neobank_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - neobank-network

  account-postgres:
    image: postgres:16
    container_name: account-postgres
    volumes:
      - account_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neobank_accounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - neobank-network

  transaction-postgres:
    image: postgres:16
    container_name: transaction-postgres
    volumes:
      - transaction_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neobank_transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - neobank-network

  card-postgres:
    image: postgres:16
    container_name: card-postgres
    volumes:
      - card_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neobank_cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - neobank-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_secret
      KC_HTTP_PORT: 8090
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8090"
    networks:
      - neobank-network
    depends_on:
      - keycloak-db

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - neobank-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - neobank-network

#  user-service:
#    build:
#      context: ../ms-user-service
#
#    container_name: ms-user-service
#
#    ports:
#      - "8081:8081"
#
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://neobank-postgres:5432/neobank_users
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8090/realms/neobank
#
#      KEYCLOAK_SERVER_URL: http://keycloak:8090
#      KEYCLOAK_REALM: neobank
#      KEYCLOAK_CLIENT_ID: user-service-admin
#      KEYCLOAK_CLIENT_SECRET: h9z6eP0vQWKSNfZiCo6oPuHeAj7VeBVM
#
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#    depends_on:
#      - neobank-postgres
#      - kafka
#      - keycloak
#
#    networks:
#      - neobank-network


volumes:
  keycloak_data:
  user_pgdata:
  account_pgdata:
  transaction_pgdata:
  card_pgdata:

networks:
  neobank-network:
    driver: bridge
