apiVersion: v1
kind: Secret
metadata:
  name: neobank-secrets
type: Opaque
data:
  # echo -n "postgres" | base64 -> cG9zdGdyZXM=
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  
  # echo -n "keycloak" | base64 -> a2V5Y2xvYWs=
  # echo -n "keycloak_secret" | base64 -> a2V5Y2xvYWtfc2VjcmV0
  keycloak-user: a2V5Y2xvYWs=
  keycloak-password: a2V5Y2xvYWtfc2VjcmV0
  
  # echo -n "unleash" | base64 -> dW5sZWFzaA==
  # echo -n "unleash_secret" | base64 -> dW5sZWFzaF9zZWNyZXQ=
  unleash-user: dW5sZWFzaA==
  unleash-password: dW5sZWFzaF9zZWNyZXQ=
  
  # echo -n "admin" | base64 -> YWRtaW4=
  grafana-user: YWRtaW4=
  grafana-password: YWRtaW4=
  
  # echo -n "elastic" | base64 -> ZWxhc3RpYw==
  # echo -n "elastic_secret" | base64 -> ZWxhc3RpY19zZWNyZXQ=
  elastic-user: ZWxhc3RpYw==
  elastic-password: ZWxhc3RpY19zZWNyZXQ=

  # Vault specific secrets
  keycloak-client-secret: UVdDQUtNMWk3U2RXS0Mzcjl4cXVJQVU2bkZNV0NsbFk=
  unleash-api-token: KjpkZXZlbG9wbWVudC4zN2ZmNDdmZTJlMDgxMmY0YWE0YTgxYzliMmY0ZGI2M2U1NWM1OTI5MzNmYjhkY2ZhNTdhYzFkZg==
  unleash-admin-api-token: KjoqLnVubGVhc2gtYWRtaW4tYXBpLXRva2Vu
  internal-api-key: bmVvYmFuay1pbnRlcm5hbC1kZXYta2V5
