apiVersion: v1
kind: Secret
metadata:
  name: neobank-secrets
type: Opaque
data:
  # echo -n "postgres" | base64
  postgres-user: cG9zdGdyZXM=
  postgres-password: eW91cl9kYl9wYXNzd29yZA==
  
  # echo -n "keycloak" | base64
  keycloak-user: a2V5Y2xvYWs=
  keycloak-password: eW91cl9rZXljbG9ha19wYXNzd29yZA==
  
  # echo -n "unleash" | base64
  unleash-user: dW5sZWFzaA==
  unleash-password: eW91cl91bmxlYXNoX3Bhc3N3b3Jk
  
  # echo -n "admin" | base64
  grafana-user: YWRtaW4=
  grafana-password: eW91cl9ncmFmYW5hX3Bhc3N3b3Jk
  
  # echo -n "elastic" | base64
  elastic-user: ZWxhc3RpYw==
  elastic-password: eW91cl9lbGFzdGljX3Bhc3N3b3Jk

  # Vault specific secrets
  keycloak-client-secret: eW91cl9rZXljbG9ha19jbGllbnRfc2VjcmV0
  unleash-api-token: eW91cl91bmxlYXNoX2FwaV90b2tlbg==
  unleash-admin-api-token: eW91cl91bmxlYXNoX2FkbWluX2FwaV90b2tlbg==
  internal-api-key: eW91cl9pbnRlcm5hbF9hcGlfa2V5
