apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  neobank-realm.json: |
    {
      "realm": "neobank",
      "enabled": true,
      "clients": [
        {
          "clientId": "user-service-admin",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "QWCAKM1i7SdWKC3r9xquIAU6nFMWCllY",
          "serviceAccountsEnabled": true,
          "directAccessGrantsEnabled": true,
          "publicClient": false,
          "protocol": "openid-connect"
        },
        {
          "clientId": "neobank-frontend",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "USER"
          },
          {
            "name": "ADMIN"
          },
          {
            "name": "KYC_MANAGER"
          },
          {
            "name": "SUPPORT"
          }
        ]
      },
      "users": [
        {
          "username": "user1@neobank.com",
          "enabled": true,
          "email": "user1@neobank.com",
          "firstName": "User",
          "lastName": "One",
          "credentials": [
            {
              "type": "password",
              "value": "user1",
              "temporary": false
            }
          ],
          "realmRoles": [
            "USER"
          ]
        },
        {
          "username": "admin@neobank.com",
          "enabled": true,
          "email": "admin@neobank.com",
          "firstName": "Admin",
          "lastName": "NeoBank",
          "credentials": [
            {
              "type": "password",
              "value": "admin",
              "temporary": false
            }
          ],
          "realmRoles": [
            "ADMIN",
            "USER"
          ]
        }
      ]
    }
