input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Add any specific filtering here if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "neobank-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
